### ISSUE TITLE
help pls asap

### ISSUE THREAD

**Issue by NickKso** [TravisLedo/LidarScanRender#1] opened 2021-04-27 20:54 UTC
ant -f D:\\LidarScanRender-master\\LidarScanRender -Dnb.internal.action.name=run run
init:
Deleting: D:\LidarScanRender-master\LidarScanRender\build\built-jar.properties
deps-jar:
Updating property file: D:\LidarScanRender-master\LidarScanRender\build\built-jar.properties
compile:
run:
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
D:\LidarScanRender-master\LidarScanRender\nbproject\build-impl.xml:1330: The following error occurred while executing this line:
D:\LidarScanRender-master\LidarScanRender\nbproject\build-impl.xml:936: Java returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by NickKso** [comment] 2021-04-27 20:56
i tried to run ur code before actually buying lidar module, just to test that program actually ran but it failed please help as soon as you can

**Comment by TravisLedo** [comment] 2021-04-27 21:04
Hey sorry I don’t really know what the issue is, but I did a quick google and saw some people asking about that. You could try some solutions from online and see if that works. 


Here is a quick example of a google result you can prob try. Other than that sorry I won’t be much help as I can't replicate the issue.

https://stackoverflow.com/questions/53795661/javafx-modular-application-java-lang-module-findexception-module-javafx-contro

**Comment by TravisLedo** [comment] 2023-07-20 00:05
@NickKso Hey sorry we couldn't figure out the issue before. Just letting you know that I updated the project now to use Gradle and all the issues with JavaFX importing should be gone. If still interested please give it a shot. I will close the issue if it works for you or if you are no longer looking at this project. Thanks!

**Closed as completed** 2024-04-03 13:44 UTC
